[build]
  command = "ng build"
  publish = "dist/myapp"

[build.processing]
  skip_processing = true

[build.environment]
  NETLIFY_SKIP_FRAMEWORKS = "true"
  NETLIFY_EXPERIMENTAL_BUILD_FRAMEWORK = "none"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
